### ISSUE TITLE
App doesn't run on TempleOS

### ISSUE THREAD

**Issue by oldspoon** [oldspoon/SET8103-group19#33]
**Describe the bug**
The application refuses to even launch, the system screams at me about something something "missing drivers".

**To Reproduce**
try launching the develop or master branch on TempleOS!

**Expected behavior**
The app just simply does not wish to run or compile!

**Screenshots**
TempleOS does not have a screenshotting module.

**Desktop (please complete the following information):**
 - OS: TempleOS
 - Browser TempleOS browser
 - Version TempleOS 5.03

**Comment by MatthewLenathen** [comment]
We do not support TempleOS. Try https://hotdoglinux.com/
